import cadquery as cq
def tower(sides=0.01):
    base = (cq.Workplane("XY")
            .rect(3600 * sides, 3600 * sides)
             .workplane(offset=1200 * sides)
             .rect(2000 * sides, 2000 * sides)
             .workplane(offset=1450 * sides)
             .rect(1000 * sides, 1000 * sides)
             .workplane(offset=3850 * sides)
             .rect(300 * sides, 300 * sides)
             .loft()
             .faces(">Z")
             .rect(300 * sides, 300 * sides)
             .workplane(offset=150 * sides)
             .circle(75 * sides)
             .loft()
             .faces(">Z")
             .circle(25 * sides)
             .extrude(500 * sides)
             )
    b = (cq.Workplane("XZ").workplane(offset=1800 * sides)
         .moveTo(1100 * sides, 0)
         .threePointArc((0, 950 * sides),(-1100 * sides, 0))
         .close()
         .extrude(-3600 * sides)
         )
    model = base.cut(b)
    b = b.rotate((0,0,0),(0,0,1),90)
    model = model.cut(b)
    c = (cq.Workplane("XY").workplane(offset=1550 * sides)
         .rect(850 * sides, 3600 * sides)
         .workplane(offset=850 * sides)
         .rect(450 * sides, 3600 * sides)
         .loft()
         )
    model = model.cut(c)
    c = c.rotate((0,0,0),(0,0,1),90)
    model = model.cut(c)
    d = (cq.Workplane("XY").workplane(offset=2850 * sides)
         .rect(300 * sides, 3600 * sides)
         .workplane(offset=1700 * sides)
         .rect(1 * sides, 3600 * sides)
         .loft()
         )
    model = model.cut(d)
    d = d.rotate((0,0,0),(0,0,1),90)
    model = model.cut(d)
    return model
def floor(sides=0.01):
    one = (cq.Workplane("XY").workplane(offset=1200 * sides)
           .rect(2000 * sides, 2000 * sides)
           .extrude(350 * sides)
           )
    two = (one.workplane(offset=1450 * sides)
           .rect(1100 * sides, 1200 * sides)
           .extrude(200 * sides)
           )
    three = (two.workplane(offset=4600 * sides)
             .rect(450 * sides, 450 * sides)
             .extrude(100 * sides)
             )
    return three
res1 = tower()
show_model(res1, cq)
res2 = floor()
show_model(res2, cq)